### ISSUE TITLE
Need linux-headers-4.14.34-rt27-v7 linux-image-4.14.34-rt27-v7

### ISSUE THREAD

**Issue by TacHuynh** [guysoft/RealtimePi#12]
I tried to install the ethercat per this github: https://github.com/koppi/mk/blob/master/Machinekit-RT-Preempt-RPI.md
Build and install IgH EtherCAT master

git clone https://github.com/koppi/ec-debianize
cd ec-debianize
git checkout for-sittner
debian/configure `uname -r`
dpkg-checkbuilddeps
debuild -uc -us

when running checkbuilddeps I got this error:
pi@realtimepi:~/ec-debianize $ dpkg-checkbuilddeps
dpkg-checkbuilddeps: error: Unmet build dependencies: linux-headers-4.14.34-rt27-v7 linux-image-4.14.34-rt27-v7

my raspberry pi
pi@realtimepi:~/ec-debianize $ uname -a
Linux realtimepi 4.14.34-rt27-v7 #2 SMP PREEMPT RT Tue Jun 12 19:20:24 UTC 2018 armv7l GNU/Linux

Please help.
Thanks,
Tac.

**Comment by guysoft** [comment]
Ok,
First, the script you are using assumes a debain system where the kernel images are supplied with [debian kernel header packstges](https://kernel-team.pages.debian.net/kernel-handbook/ch-packaging.html). Raspbian has a package ``sudo apt-get install raspberrypi-kernel-headers`` but this would only install the kernel shipped with raspbian.
You can't debianize the process because is not shipped as a deb package.
A PR of a building debian package would be welcomed, I have no time to do it.

You will need to file a bug there that you can't build ``ec-debianize`` even if you have the kenrel headers because they are not in the package.

A workaround would be to download the sources, then patch them
Assuming you are using latest release which is RealtimePi 0.3.0 

```bash
cd /home/pi
git clone https://github.com/raspberrypi/linux.git
cd linux 
# taken from release config file
git checkout d2cf662756932ca61f61b9552272bb36cde5e966
patch -p1 < /home/pi/patches/0001-usb-dwc_otg-fix-system-lockup-when-interrupts-are-th.patch
xzcat ../patch-4.14.34-rt27.patch.xz | patch -p1
```

This does bring the issue that the build at the moment does not save the sources or headers of the build.
There are two ways to solve this in the long run - 
1. Make a script that downloads the kernel source of the build
2. Ship only the headers somewhere.

This would give you the sources for 0.3.0 including the headers, but not as a debain package.
For 0.4.0 I could add a script to pull the right kernel.

**Comment by guysoft** [comment]
II Suggest you use the nightly, and then you can just checkout the sources off https://github.com/raspberrypi/linux/tree/rpi-4.14.y-rt .
That would make it easier

**Comment by guysoft** [comment]
Closing due to no reply
