### ISSUE TITLE
Examples on utilizing this real time OS?

### ISSUE THREAD

**Issue by Patrickyp** [guysoft/RealtimePi#14]
I'm new to real time OS.  Do you have some simple sample code or example to demonstrate real time programming in say C/C++?  How do you use this OS?

THanks..

**Comment by guysoft** [comment]
Quick google gives: https://www.tldp.org/HOWTO/RTLinux-HOWTO-4.html

I personally used it for [jack2](http://jackaudio.org/), so I did not have any need to write my own software.
But since this is out of the scope of the disto I can't really help beyond that. 
If someone wants to extend the wiki with use cases they are welcome.

You use it the same way you would use RTlinux, which is what it is. You can ask them for examples.

**Comment by guysoft** [comment]
Closing if no reply
