### ISSUE TITLE
Repository Request

### ISSUE THREAD

**Issue by brandflake11** [guysoft/RealtimePi#27]
This looks like the best way to easily get a realtime kernel for RaspberryPi OS. Is there anyway that the project could make a repository vanilla RaspberryPi OS (sounds tasty!) users can add to use the realtime kernel to save build time?

**Comment by guysoft** [comment]
Yes there is, the release also includes a tar.gz file you can extract over Rpi OS, ans potentially other distros, with the realtime kernel

**Comment by brandflake11** [comment]
Thank you, that's sweet! I think it would also be very nice and convenient to make a .deb file for Raspberry Pi OS.

**Comment by guysoft** [comment]
1. deb file would restrict it to debian-based distros. This should also work with Arch, for example.
2. A deb usually needs to use debian build methodology (at least, that is the only benefit I see here, I don't mean what checkinstall does), I really doubt that is needed here. It might be relevant for Rpi-foundation because they could have it as a package that people install, similar to how debian/ubuntu have the linux-image packages. However they already made it clear they don't want to maintain a realtime kernel.

**Comment by brandflake11** [comment]
Okay, this makes sense, thanks for the detailed response!

I'll figure out how to do it manually then!

**Comment by guysoft** [comment]
@brandflake11
What you do is extract it over your root.
```
cd /
sudo wget http://unofficialpi.org/Distros/RealtimePi/2019-12-17_realtimepi-kernel-4.19.71.tar.gz
sudo tar xzvf 2019-12-17_realtimepi-kernel-4.19.71.tar.gz
reboot
```
Note that this kernel is not that new, i don't think it will work on some Pi 4s. The nightly might.

**Comment by brandflake11** [comment]
@guysoft Thank you for the help. I'll make sure to backup /boot first!
